package com.pangochain.backend.security.alert;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/** An anomaly flagged by the audit analysis sweep. */
@Entity
@Table(name = "security_alerts")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class SecurityAlert {

    public enum Severity { LOW, MEDIUM, HIGH }

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private Severity severity = Severity.LOW;

    @Column(name = "alert_type", nullable = false)
    private String alertType;

    @Column(nullable = false, columnDefinition = "TEXT")
    private String description;

    @Column(name = "actor_id")
    private UUID actorId;

    @Column(name = "actor_label")
    private String actorLabel;

    private Double metric;

    @Column(name = "fabric_tx_id")
    private String fabricTxId;

    /** Stable signature so re-runs replace rather than duplicate the same finding. */
    @Column
    private String signature;

    @Column(nullable = false)
    @Builder.Default
    private boolean acknowledged = false;

    @Column(name = "auto_generated", nullable = false)
    @Builder.Default
    private boolean autoGenerated = true;

    @Column(name = "detected_at", nullable = false, updatable = false)
    private Instant detectedAt;

    @PrePersist
    void prePersist() { if (detectedAt == null) detectedAt = Instant.now(); }
}
