package com.pangochain.backend.security.alert;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;

import java.util.List;
import java.util.UUID;

public interface SecurityAlertRepository extends JpaRepository<SecurityAlert, UUID> {

    List<SecurityAlert> findAllByOrderBySeverityDescDetectedAtDesc();

    long countByAcknowledgedFalse();

    /** Auto-generated, still-unacknowledged alerts are cleared before each fresh sweep. */
    @Modifying
    @Query("DELETE FROM SecurityAlert a WHERE a.autoGenerated = true AND a.acknowledged = false")
    void deleteUnacknowledgedAuto();
}
