// ─── Demo / seed data for frontend showcase ──────────────────────────────────
// Used when the backend is not running. Activated by the demo login.

export const DEMO_USER = {
  id: 'demo-user-001',
  email: 'sarah.chen@firma.com',
  fullName: 'Sarah Chen',
  role: 'SENIOR_ASSOCIATE' as const,
  firmId: 'firm-a-001',
  mfaEnabled: true,
}

export const MOCK_CASES = [
  {
    id: 'case-001',
    title: 'Meridian Capital Partners — Series C Acquisition',
    caseType: 'Corporate M&A',
    status: 'ACTIVE',
    clientName: 'Meridian Capital Partners LLC',
    counterparty: 'NovaTech Solutions Inc.',
    matterValue: '$142,000,000',
    leadAttorney: 'Sarah Chen',
    documents: 34,
    createdAt: '2026-01-08T09:00:00Z',
    lastActivity: '2026-04-25T14:30:00Z',
    description: 'Cross-border acquisition of NovaTech Solutions. Due diligence phase in progress.',
    tags: ['M&A', 'Due Diligence', 'Cross-border'],
  },
  {
    id: 'case-002',
    title: 'Hartwell v. Pinnacle Insurance Group',
    caseType: 'Commercial Litigation',
    status: 'ACTIVE',
    clientName: 'Hartwell Industries',
    counterparty: 'Pinnacle Insurance Group',
    matterValue: '$8,500,000',
    leadAttorney: 'Michael Torres',
    documents: 127,
    createdAt: '2025-11-03T10:15:00Z',
    lastActivity: '2026-04-27T11:00:00Z',
    description: 'Commercial property insurance dispute following warehouse fire. Trial date set for Q3 2026.',
    tags: ['Litigation', 'Insurance', 'Trial'],
  },
  {
    id: 'case-003',
    title: 'Solaris Tech — Patent Portfolio Licensing',
    caseType: 'Intellectual Property',
    status: 'ACTIVE',
    clientName: 'Solaris Technologies Inc.',
    counterparty: 'Multiple licensees',
    matterValue: '$25,000,000',
    leadAttorney: 'Sarah Chen',
    documents: 56,
    createdAt: '2026-02-14T08:30:00Z',
    lastActivity: '2026-04-22T16:45:00Z',
    description: 'Negotiating licensing agreements for 12-patent AI/ML portfolio across 6 jurisdictions.',
    tags: ['IP', 'Patents', 'Licensing'],
  },
  {
    id: 'case-004',
    title: 'BlueRock REIT — Commercial Lease Portfolio Review',
    caseType: 'Real Estate',
    status: 'ACTIVE',
    clientName: 'BlueRock REIT Management',
    counterparty: 'Various tenants',
    matterValue: '$3,200,000',
    leadAttorney: 'Amanda Patel',
    documents: 89,
    createdAt: '2026-03-01T09:00:00Z',
    lastActivity: '2026-04-26T10:20:00Z',
    description: 'Annual review and renegotiation of 23 commercial leases across 4 office parks.',
    tags: ['Real Estate', 'Leasing', 'Review'],
  },
  {
    id: 'case-005',
    title: 'Axiom Pharma — FDA Compliance & Regulatory',
    caseType: 'Regulatory',
    status: 'ACTIVE',
    clientName: 'Axiom Pharmaceuticals',
    counterparty: 'U.S. FDA',
    matterValue: 'N/A',
    leadAttorney: 'David Kim',
    documents: 201,
    createdAt: '2025-09-15T11:00:00Z',
    lastActivity: '2026-04-24T09:15:00Z',
    description: 'Ongoing regulatory compliance advisory for drug manufacturing facility audit response.',
    tags: ['Regulatory', 'FDA', 'Compliance'],
  },
  {
    id: 'case-006',
    title: 'GlobalNet — Employment Class Action Defense',
    caseType: 'Employment Law',
    status: 'ACTIVE',
    clientName: 'GlobalNet Communications',
    counterparty: 'Class of 340 plaintiffs',
    matterValue: '$15,000,000',
    leadAttorney: 'Sarah Chen',
    documents: 312,
    createdAt: '2025-07-22T14:00:00Z',
    lastActivity: '2026-04-23T17:00:00Z',
    description: 'Class action defense on wrongful termination and wage-and-hour claims. Discovery phase.',
    tags: ['Employment', 'Class Action', 'Defense'],
  },
  {
    id: 'case-007',
    title: 'Vantage Foods — Supply Chain Contract Dispute',
    caseType: 'Contract Dispute',
    status: 'CLOSED',
    clientName: 'Vantage Foods International',
    counterparty: 'Pacific Agro Suppliers Ltd.',
    matterValue: '$2,100,000',
    leadAttorney: 'Michael Torres',
    documents: 45,
    createdAt: '2025-04-10T10:00:00Z',
    lastActivity: '2026-01-15T16:00:00Z',
    description: 'Breach of supply agreement. Settled in mediation for $1.4M. Case closed.',
    tags: ['Contract', 'Settlement', 'Closed'],
  },
  {
    id: 'case-008',
    title: 'ClearPath Ventures — Joint Venture Agreement',
    caseType: 'Corporate',
    status: 'CLOSED',
    clientName: 'ClearPath Ventures',
    counterparty: 'Omega Infrastructure Fund',
    matterValue: '$50,000,000',
    leadAttorney: 'Amanda Patel',
    documents: 78,
    createdAt: '2025-06-01T09:00:00Z',
    lastActivity: '2025-12-20T12:00:00Z',
    description: 'Joint venture structuring for renewable energy infrastructure fund. Completed successfully.',
    tags: ['Corporate', 'JV', 'Energy'],
  },
  {
    id: 'case-009',
    title: 'Nexus Fintech — Regulatory Sandbox Application',
    caseType: 'Fintech Regulatory',
    status: 'ACTIVE',
    clientName: 'Nexus Fintech Ltd.',
    counterparty: 'FCA / SEC',
    matterValue: 'N/A',
    leadAttorney: 'David Kim',
    documents: 33,
    createdAt: '2026-03-20T08:00:00Z',
    lastActivity: '2026-04-20T14:00:00Z',
    description: 'Regulatory sandbox application for novel DeFi payment product in US and UK markets.',
    tags: ['Fintech', 'Regulatory', 'DeFi'],
  },
]

export const MOCK_DOCUMENTS = [
  { id: 'doc-001', name: 'Meridian_APA_Draft_v3.pdf', caseId: 'case-001', caseTitle: 'Meridian Capital Partners', type: 'Agreement', size: '2.4 MB', uploadedAt: '2026-04-20T10:00:00Z', status: 'ACTIVE', uploadedBy: 'Sarah Chen' },
  { id: 'doc-002', name: 'NovaTech_Due_Diligence_Report.pdf', caseId: 'case-001', caseTitle: 'Meridian Capital Partners', type: 'Report', size: '8.1 MB', uploadedAt: '2026-04-18T14:30:00Z', status: 'ACTIVE', uploadedBy: 'Michael Torres' },
  { id: 'doc-003', name: 'Hartwell_Expert_Witness_Statement.docx', caseId: 'case-002', caseTitle: 'Hartwell v. Pinnacle', type: 'Statement', size: '512 KB', uploadedAt: '2026-04-15T09:15:00Z', status: 'ACTIVE', uploadedBy: 'Sarah Chen' },
  { id: 'doc-004', name: 'Solaris_Patent_Valuation_2026.xlsx', caseId: 'case-003', caseTitle: 'Solaris Tech', type: 'Financial', size: '1.2 MB', uploadedAt: '2026-04-10T11:00:00Z', status: 'ACTIVE', uploadedBy: 'Amanda Patel' },
  { id: 'doc-005', name: 'GlobalNet_Employee_Records_Redacted.zip', caseId: 'case-006', caseTitle: 'GlobalNet Class Action', type: 'Evidence', size: '45.3 MB', uploadedAt: '2026-04-05T16:00:00Z', status: 'ACTIVE', uploadedBy: 'David Kim' },
  { id: 'doc-006', name: 'BlueRock_Lease_Matrix_Q2.xlsx', caseId: 'case-004', caseTitle: 'BlueRock REIT', type: 'Contract', size: '890 KB', uploadedAt: '2026-04-02T13:00:00Z', status: 'ACTIVE', uploadedBy: 'Sarah Chen' },
]

export const MOCK_AUDIT = [
  { id: 'aud-001', eventType: 'DOC_REGISTERED', actor: 'Sarah Chen', resource: 'Meridian_APA_Draft_v3.pdf', timestamp: '2026-04-20T10:02:11Z', txId: '0x4f2a...c891', org: 'FirmAMSP' },
  { id: 'aud-002', eventType: 'ACCESS_GRANTED', actor: 'Sarah Chen', resource: 'NovaTech_Due_Diligence_Report.pdf', timestamp: '2026-04-18T14:35:02Z', txId: '0x7e1b...d432', org: 'FirmAMSP' },
  { id: 'aud-003', eventType: 'DOC_VIEWED', actor: 'Michael Torres', resource: 'Hartwell_Expert_Witness_Statement.docx', timestamp: '2026-04-17T09:22:44Z', txId: '0x2c9f...a110', org: 'FirmAMSP' },
  { id: 'aud-004', eventType: 'ACCESS_REVOKED', actor: 'Sarah Chen', resource: 'Solaris_Patent_Valuation_2026.xlsx', timestamp: '2026-04-16T16:10:33Z', txId: '0x8a3d...f220', org: 'FirmAMSP' },
  { id: 'aud-005', eventType: 'CASE_REGISTERED', actor: 'Amanda Patel', resource: 'BlueRock REIT', timestamp: '2026-03-01T09:05:17Z', txId: '0x1b7c...e543', org: 'FirmAMSP' },
]

export const MOCK_STATS = {
  activeCases: 7,
  totalDocuments: 975,
  unreadMessages: 3,
  auditEvents: 1248,
}
